name: Under
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8641010706778616
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d0578'
    - '#100070'
    - '#180078'
    - '#1b0378'
    - '#1b0379'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
